close all;clear all;clc;

A0=220;
Bb0=A0*2^(1/12);
B0=Bb0*2^(1/12);
C0=B0*2^(1/12);
Db0=C0*2^(1/12);
D0=Db0*2^(1/12);
Eb0=D0*2^(1/12);
E0=Eb0*2^(1/12);
F0=E0*2^(1/12);
Gb0=F0*2^(1/12);
G0=Gb0*2^(1/12);
Ab1=G0*2^(1/12);
A1=440;
Bb1=A1*2^(1/12);
B1=Bb1*2^(1/12);
C1=B1*2^(1/12);
Db1=C1*2^(1/12);
D1=Db1*2^(1/12);
Eb1=D1*2^(1/12);
E1=Eb1*2^(1/12);
F1=E1*2^(1/12);
Gb1=F1*2^(1/12);
G1=Gb1*2^(1/12);
Ab2=G1*2^(1/12);
A_1=110;
Bb_1=A_1*2^(1/12);
B_1=Bb_1*2^(1/12);
C_1=B_1*2^(1/12);
Db_1=C_1*2^(1/12);
D_1=Db_1*2^(1/12);
Eb_1=D_1*2^(1/12);
E_1=Eb_1*2^(1/12);
F_1=E_1*2^(1/12);
Gb_1=F_1*2^(1/12);
G_1=Gb_1*2^(1/12);
Ab0=G_1*2^(1/12);

% 1=Eb
mi_1=G_1;
fa_1=Ab0;
so_1=Bb0;
la_1=C0;
si_1=D0;
do0=Eb0;
re0=F0;
mi0=G0;
fa0=Ab1;
so0=Bb1;
la0=C1;
si0=D1;
do1=Eb1;

beat=0.5;
FS=44100;

rise_time=1/9;
set_time=1/18;
disappear_time=1/6;
% 王菲的《致青春》。似乎弄得有些长了……可以听出旋律，但实在算不上悦耳……
tones={...
    AddDecay(GenerateToneWithHarmonic(do0,beat*0.75,FS),...
    rise_time, set_time,disappear_time),...
    AddDecay(GenerateToneWithHarmonic(si_1,beat/4,FS),...
    rise_time, set_time,disappear_time),...
    AddDecay(GenerateToneWithHarmonic(do0,beat*0.75,FS),...
    rise_time, set_time,disappear_time),...
    AddDecay(GenerateToneWithHarmonic(si_1,beat/4,FS),...
    rise_time, set_time,disappear_time),...
    AddDecay(GenerateToneWithHarmonic(do0,beat*0.75,FS),...
    rise_time, set_time,disappear_time),...
    AddDecay(GenerateToneWithHarmonic(la_1,beat/4,FS),...
    rise_time, set_time,disappear_time),...
    AddDecay(GenerateToneWithHarmonic(do0,beat,FS),...
    rise_time,set_time,disappear_time),...
    AddDecay(GenerateToneWithHarmonic(mi0,beat*1.5,FS),...
    rise_time,set_time,disappear_time),...
    AddDecay(GenerateToneWithHarmonic(re0,beat/2,FS),...
    rise_time,set_time,disappear_time),...
    AddDecay(GenerateToneWithHarmonic(re0,beat/2,FS),...
    rise_time,set_time,disappear_time),...
    AddDecay(GenerateToneWithHarmonic(si_1,beat*2.5,FS),...
    rise_time,set_time,disappear_time),...
    AddDecay(GenerateToneWithHarmonic(0,beat*3,FS),...
    rise_time,set_time,disappear_time),...
    ...
    AddDecay(GenerateToneWithHarmonic(si_1,beat*0.75,FS),...
    rise_time,set_time,disappear_time),...
    AddDecay(GenerateToneWithHarmonic(la_1/2^(1/12),beat/4,FS),...
    rise_time,set_time,disappear_time),...
    AddDecay(GenerateToneWithHarmonic(si_1,beat*0.75,FS),...
    rise_time,set_time,disappear_time),...
    AddDecay(GenerateToneWithHarmonic(la_1,beat/4,FS),...
    rise_time,set_time,disappear_time),...
    AddDecay(GenerateToneWithHarmonic(si_1,beat*0.75,FS),...
    rise_time,set_time,disappear_time),...
    AddDecay(GenerateToneWithHarmonic(mi_1,beat/4,FS),...
    rise_time,set_time,disappear_time),...
    AddDecay(GenerateToneWithHarmonic(re0,beat,FS),...
    rise_time,set_time,disappear_time),...
    AddDecay(GenerateToneWithHarmonic(do0,beat*1.5,FS),...
    rise_time,set_time,disappear_time),...
    AddDecay(GenerateToneWithHarmonic(si_1,beat/2,FS),...
    rise_time,set_time,disappear_time),...
    AddDecay(GenerateToneWithHarmonic(si_1,beat/2,FS),...
    rise_time,set_time,disappear_time),...
    AddDecay(GenerateToneWithHarmonic(la_1,beat*2.5,FS),...
    rise_time,set_time,disappear_time),...
    AddDecay(GenerateToneWithHarmonic(0,beat*3,FS),...
    rise_time,set_time,disappear_time),...
    ...
    AddDecay(GenerateToneWithHarmonic(la_1,beat*0.75,FS),...
    rise_time,set_time,disappear_time),...
    AddDecay(GenerateToneWithHarmonic(si_1,beat/4,FS),...
    rise_time,set_time,disappear_time),...
    AddDecay(GenerateToneWithHarmonic(do0,beat/2,FS),...
    rise_time,set_time,disappear_time),...
    AddDecay(GenerateToneWithHarmonic(si_1,beat/2,FS),...
    rise_time,set_time,disappear_time),...
    AddDecay(GenerateToneWithHarmonic(do0,beat*2,FS),...
    rise_time,set_time,disappear_time),...
    AddDecay(GenerateToneWithHarmonic(si_1,beat/2,FS),...
    rise_time,set_time,disappear_time),...
    AddDecay(GenerateToneWithHarmonic(do0,beat/2,FS),...
    rise_time,set_time,disappear_time),...
    AddDecay(GenerateToneWithHarmonic(la_1,beat/2,FS),...
    rise_time,set_time,disappear_time),...
    AddDecay(GenerateToneWithHarmonic(si_1,beat/2,FS),...
    rise_time,set_time,disappear_time),...
    AddDecay(GenerateToneWithHarmonic(do0,beat/2,FS),...
    rise_time,set_time,disappear_time),...
    AddDecay(GenerateToneWithHarmonic(mi0,beat/2,FS),...
    rise_time,set_time,disappear_time),...
    AddDecay(GenerateToneWithHarmonic(re0,beat*2.5,FS),...
    rise_time,set_time,disappear_time),...
    AddDecay(GenerateToneWithHarmonic(0,beat*3,FS),...
    rise_time,set_time,disappear_time),...
    ...
    AddDecay(GenerateToneWithHarmonic(si_1,beat*0.75,FS),...
    rise_time,set_time,disappear_time),...
    AddDecay(GenerateToneWithHarmonic(la_1/2^(1/12),beat/4,FS),...
    rise_time,set_time,disappear_time),...
    AddDecay(GenerateToneWithHarmonic(si_1,beat*0.75,FS),...
    rise_time,set_time,disappear_time),...
    AddDecay(GenerateToneWithHarmonic(la_1,beat/4,FS),...
    rise_time,set_time,disappear_time),...
    AddDecay(GenerateToneWithHarmonic(si_1,beat*0.75,FS),...
    rise_time,set_time,disappear_time),...
    AddDecay(GenerateToneWithHarmonic(mi_1,beat/4,FS),...
    rise_time,set_time,disappear_time),...
    AddDecay(GenerateToneWithHarmonic(re0,beat,FS),...
    rise_time,set_time,disappear_time),...
    AddDecay(GenerateToneWithHarmonic(do0,beat*1.5,FS),...
    rise_time,set_time,disappear_time),...
    AddDecay(GenerateToneWithHarmonic(si_1,beat/2,FS),...
    rise_time,set_time,disappear_time),...
    AddDecay(GenerateToneWithHarmonic(si_1,beat/2,FS),...
    rise_time,set_time,disappear_time),...
    AddDecay(GenerateToneWithHarmonic(la_1,beat*2.5,FS),...
    rise_time,set_time,disappear_time),...
    AddDecay(GenerateToneWithHarmonic(0,beat*3,FS),...
    rise_time,set_time, disappear_time),...
    ...
    AddDecay(GenerateToneWithHarmonic(la_1,beat*0.75,FS),...
    rise_time,set_time,disappear_time),...
    AddDecay(GenerateToneWithHarmonic(si_1,beat/4,FS),...
    rise_time,set_time,disappear_time),...
    AddDecay(GenerateToneWithHarmonic(do0,beat*0.75,FS),...
    rise_time,set_time,disappear_time),...
    AddDecay(GenerateToneWithHarmonic(si_1,beat/4,FS),...
    rise_time,set_time,disappear_time),...
    AddDecay(GenerateToneWithHarmonic(do0,beat*0.75,FS),...
    rise_time,set_time,disappear_time),...
    AddDecay(GenerateToneWithHarmonic(mi_1,beat/4,FS),...
    rise_time,set_time,disappear_time),...
    AddDecay(GenerateToneWithHarmonic(do0,beat,FS),...
    rise_time,set_time,disappear_time),...
    AddDecay(GenerateToneWithHarmonic(mi0,beat*1.5,FS),...
    rise_time,set_time,disappear_time),...
    AddDecay(GenerateToneWithHarmonic(re0,beat/2,FS),...
    rise_time,set_time,disappear_time),...
    AddDecay(GenerateToneWithHarmonic(re0,beat/2,FS),...
    rise_time,set_time,disappear_time),...
    AddDecay(GenerateToneWithHarmonic(si_1,beat*2.5,FS),...
    rise_time,set_time,disappear_time),...
    AddDecay(GenerateToneWithHarmonic(0,beat*3,FS),...
    rise_time,set_time,disappear_time),...
    ...
    AddDecay(GenerateToneWithHarmonic(si_1,beat*0.75,FS),...
    rise_time,set_time,disappear_time),...
    AddDecay(GenerateToneWithHarmonic(la_1/2^(1/12),beat/4,FS),...
    rise_time,set_time,disappear_time),...
    AddDecay(GenerateToneWithHarmonic(si_1,beat*0.75,FS),...
    rise_time,set_time,disappear_time),...
    AddDecay(GenerateToneWithHarmonic(la_1,beat/4,FS),...
    rise_time,set_time,disappear_time),...
    AddDecay(GenerateToneWithHarmonic(si_1,beat*0.75,FS),...
    rise_time,set_time,disappear_time),...
    AddDecay(GenerateToneWithHarmonic(mi_1,beat/4,FS),...
    rise_time,set_time,disappear_time),...
    AddDecay(GenerateToneWithHarmonic(re0,beat,FS),...
    rise_time,set_time,disappear_time),...
    AddDecay(GenerateToneWithHarmonic(do0,beat*1.5,FS),...
    rise_time,set_time,disappear_time),...
    AddDecay(GenerateToneWithHarmonic(si_1,beat/2,FS),...
    rise_time,set_time,disappear_time),...
    AddDecay(GenerateToneWithHarmonic(si_1,beat/2,FS),...
    rise_time,set_time,disappear_time),...
    AddDecay(GenerateToneWithHarmonic(la_1,beat*2.5,FS),...
    rise_time,set_time,disappear_time),...
    AddDecay(GenerateToneWithHarmonic(0,beat*3,FS),...
    rise_time,set_time, disappear_time),...
    ...
    AddDecay(GenerateToneWithHarmonic(la_1,beat*0.75,FS),...
    rise_time,set_time,disappear_time),...
    AddDecay(GenerateToneWithHarmonic(si_1,beat/4,FS),...
    rise_time,set_time,disappear_time),...
    AddDecay(GenerateToneWithHarmonic(do0,beat*0.75,FS),...
    rise_time,set_time,disappear_time),...
    AddDecay(GenerateToneWithHarmonic(si_1,beat/4,FS),...
    rise_time,set_time,disappear_time),...
    AddDecay(GenerateToneWithHarmonic(do0,beat*2,FS),...
    rise_time,set_time,disappear_time),...
    AddDecay(GenerateToneWithHarmonic(si_1,beat/2,FS),...
    rise_time,set_time,disappear_time),...
    AddDecay(GenerateToneWithHarmonic(do0,beat/2,FS),...
    rise_time,set_time,disappear_time),...
    AddDecay(GenerateToneWithHarmonic(la_1,beat/2,FS),...
    rise_time,set_time,disappear_time),...
    AddDecay(GenerateToneWithHarmonic(si_1,beat/2,FS),...
    rise_time,set_time,disappear_time),...
    AddDecay(GenerateToneWithHarmonic(do0,beat/2,FS),...
    rise_time,set_time,disappear_time),...
    AddDecay(GenerateToneWithHarmonic(mi0,beat/2,FS),...
    rise_time,set_time,disappear_time),...
    AddDecay(GenerateToneWithHarmonic(re0,beat*2.5,FS),...
    rise_time,set_time,disappear_time),...
    AddDecay(GenerateToneWithHarmonic(0,beat*3,FS),...
    rise_time,set_time,disappear_time),...
    ...
    AddDecay(GenerateToneWithHarmonic(si_1,beat*0.75,FS),...
    rise_time,set_time,disappear_time),...
    AddDecay(GenerateToneWithHarmonic(la_1/2^(1/12),beat/4,FS),...
    rise_time,set_time,disappear_time),...
    AddDecay(GenerateToneWithHarmonic(si_1,beat*0.75,FS),...
    rise_time,set_time,disappear_time),...
    AddDecay(GenerateToneWithHarmonic(la_1,beat/4,FS),...
    rise_time,set_time,disappear_time),...
    AddDecay(GenerateToneWithHarmonic(si_1,beat*0.75,FS),...
    rise_time,set_time,disappear_time),...
    AddDecay(GenerateToneWithHarmonic(mi_1,beat/4,FS),...
    rise_time,set_time,disappear_time),...
    AddDecay(GenerateToneWithHarmonic(re0,beat,FS),...
    rise_time,set_time,disappear_time),...
    AddDecay(GenerateToneWithHarmonic(do0,beat*1.5,FS),...
    rise_time,set_time,disappear_time),...
    AddDecay(GenerateToneWithHarmonic(si_1,beat/2,FS),...
    rise_time,set_time,disappear_time),...
    AddDecay(GenerateToneWithHarmonic(si_1,beat/2,FS),...
    rise_time,set_time,disappear_time),...
    AddDecay(GenerateToneWithHarmonic(la_1,beat*4.5,FS),...
    rise_time,set_time,disappear_time),...
    AddDecay(GenerateToneWithHarmonic(0,beat,FS),...
    rise_time,set_time, disappear_time),...
    ...
    ...
    AddDecay(GenerateToneWithHarmonic(do0,beat*3,FS),...
    rise_time,set_time, disappear_time),...
    AddDecay(GenerateToneWithHarmonic(la_1,beat*3,FS),...
    rise_time,set_time, disappear_time),...
    AddDecay(GenerateToneWithHarmonic(si_1,beat*3,FS),...
    rise_time,set_time, disappear_time),...
    AddDecay(GenerateToneWithHarmonic(so_1,beat*3,FS),...
    rise_time,set_time, disappear_time),...
    AddDecay(GenerateToneWithHarmonic(do0,beat*3,FS),...
    rise_time,set_time, disappear_time),...
    AddDecay(GenerateToneWithHarmonic(la_1,beat*3,FS),...
    rise_time,set_time, disappear_time),...
    ...
    AddDecay(GenerateToneWithHarmonic(si_1,beat*1.5,FS),...
    rise_time,set_time, disappear_time),...
    AddDecay(GenerateToneWithHarmonic(la_1,beat/2,FS),...
    rise_time,set_time, disappear_time),...
    AddDecay(GenerateToneWithHarmonic(so_1,beat/2,FS),...
    rise_time,set_time, disappear_time),...
    AddDecay(GenerateToneWithHarmonic(mi_1,beat/2,FS),...
    rise_time,set_time, disappear_time),...
    AddDecay(GenerateToneWithHarmonic(mi_1,beat*2,FS),...
    rise_time,set_time, disappear_time),...
    AddDecay(GenerateToneWithHarmonic(0,beat,FS),...
    rise_time,set_time, disappear_time),...
    ...
    AddDecay(GenerateToneWithHarmonic(do0,beat*3,FS),...
    rise_time,set_time, disappear_time),...
    AddDecay(GenerateToneWithHarmonic(la_1,beat,FS),...
    rise_time,set_time, disappear_time),...
    AddDecay(GenerateToneWithHarmonic(0,beat*2,FS),...
    rise_time,set_time, disappear_time),...
    AddDecay(GenerateToneWithHarmonic(si_1,beat*2.5,FS),...
    rise_time,set_time, disappear_time),...
    AddDecay(GenerateToneWithHarmonic(so_1,beat/2,FS),...
    rise_time,set_time, disappear_time),...
    AddDecay(GenerateToneWithHarmonic(0,beat*3,FS),...
    rise_time,set_time, disappear_time),...
    AddDecay(GenerateToneWithHarmonic(do0,beat*3,FS),...
    rise_time,set_time, disappear_time),...
    AddDecay(GenerateToneWithHarmonic(la_1,beat,FS),...
    rise_time,set_time, disappear_time),...
    AddDecay(GenerateToneWithHarmonic(0,beat/2,FS),...
    rise_time,set_time, disappear_time),...
    AddDecay(GenerateToneWithHarmonic(si_1,beat/2,FS),...
    rise_time,set_time, disappear_time),...
    AddDecay(GenerateToneWithHarmonic(do0,beat,FS),...
    rise_time,set_time, disappear_time),...
    AddDecay(GenerateToneWithHarmonic(si_1,beat/2,FS),...
    rise_time,set_time, disappear_time),...
    AddDecay(GenerateToneWithHarmonic(mi0,beat*7.5,FS),...
    rise_time,set_time, disappear_time),...
    AddDecay(GenerateToneWithHarmonic(0,beat*4,FS),...
    rise_time,set_time, disappear_time),...
    ...
    ...
    AddDecay(GenerateToneWithHarmonic(mi0,beat/2,FS),...
    rise_time,set_time, disappear_time),...
    AddDecay(GenerateToneWithHarmonic(la0,beat/2,FS),...
    rise_time,set_time, disappear_time),...
    AddDecay(GenerateToneWithHarmonic(la0,beat/2,FS),...
    rise_time,set_time, disappear_time),...
    AddDecay(GenerateToneWithHarmonic(so0,beat/2,FS),...
    rise_time,set_time, disappear_time),...
    AddDecay(GenerateToneWithHarmonic(so0,beat/2,FS),...
    rise_time,set_time, disappear_time),...
    AddDecay(GenerateToneWithHarmonic(re0,beat/2,FS),...
    rise_time,set_time, disappear_time),...
    AddDecay(GenerateToneWithHarmonic(mi0,beat*3,FS),...
    rise_time,set_time, disappear_time),...
    ...
    AddDecay(GenerateToneWithHarmonic(mi0,beat/2,FS),...
    rise_time,set_time, disappear_time),...
    AddDecay(GenerateToneWithHarmonic(la0,beat/2,FS),...
    rise_time,set_time, disappear_time),...
    AddDecay(GenerateToneWithHarmonic(la0,beat/2,FS),...
    rise_time,set_time, disappear_time),...
    AddDecay(GenerateToneWithHarmonic(so0,beat/2,FS),...
    rise_time,set_time, disappear_time),...
    AddDecay(GenerateToneWithHarmonic(so0,beat/2,FS),...
    rise_time,set_time, disappear_time),...
    AddDecay(GenerateToneWithHarmonic(re0,beat/2,FS),...
    rise_time,set_time, disappear_time),...
    AddDecay(GenerateToneWithHarmonic(mi0,beat*2,FS),...
    rise_time,set_time, disappear_time),...
    AddDecay(GenerateToneWithHarmonic(0,beat/2,FS),...
    rise_time,set_time, disappear_time),...
    ...
    AddDecay(GenerateToneWithHarmonic(mi_1,beat/2,FS),...
    rise_time,set_time, disappear_time),...
    AddDecay(GenerateToneWithHarmonic(fa0,beat/2,FS),...
    rise_time,set_time, disappear_time),...
    AddDecay(GenerateToneWithHarmonic(fa0,beat/2,FS),...
    rise_time,set_time, disappear_time),...
    AddDecay(GenerateToneWithHarmonic(fa0,beat/2,FS),...
    rise_time,set_time, disappear_time),...
    AddDecay(GenerateToneWithHarmonic(mi0,beat/2,FS),...
    rise_time,set_time, disappear_time),...
    AddDecay(GenerateToneWithHarmonic(re0,beat/2,FS),...
    rise_time,set_time, disappear_time),...
    AddDecay(GenerateToneWithHarmonic(do0,beat/2,FS),...
    rise_time,set_time, disappear_time),...
    AddDecay(GenerateToneWithHarmonic(si_1,beat*2,FS),...
    rise_time,set_time, disappear_time),...
    AddDecay(GenerateToneWithHarmonic(si_1,beat/2,FS),...
    rise_time,set_time, disappear_time),...
    AddDecay(GenerateToneWithHarmonic(si_1,beat/2,FS),...
    rise_time,set_time, disappear_time),...
    AddDecay(GenerateToneWithHarmonic(do0,beat*2,FS),...
    rise_time,set_time, disappear_time),...
    AddDecay(GenerateToneWithHarmonic(re0,beat,FS),...
    rise_time,set_time, disappear_time),...
    AddDecay(GenerateToneWithHarmonic(mi0,beat*3,FS),...
    rise_time,set_time, disappear_time),...
    ...
    AddDecay(GenerateToneWithHarmonic(mi0,beat/2,FS),...
    rise_time,set_time, disappear_time),...
    AddDecay(GenerateToneWithHarmonic(la0,beat/2,FS),...
    rise_time,set_time, disappear_time),...
    AddDecay(GenerateToneWithHarmonic(la0,beat/2,FS),...
    rise_time,set_time, disappear_time),...
    AddDecay(GenerateToneWithHarmonic(so0,beat/2,FS),...
    rise_time,set_time, disappear_time),...
    AddDecay(GenerateToneWithHarmonic(so0,beat/2,FS),...
    rise_time,set_time, disappear_time),...
    AddDecay(GenerateToneWithHarmonic(re0,beat/2,FS),...
    rise_time,set_time, disappear_time),...
    AddDecay(GenerateToneWithHarmonic(mi0,beat*2,FS),...
    rise_time,set_time, disappear_time),...
    AddDecay(GenerateToneWithHarmonic(0,beat/2,FS),...
    rise_time,set_time, disappear_time),...
    ...
    AddDecay(GenerateToneWithHarmonic(mi0,beat/2,FS),...
    rise_time,set_time, disappear_time),...
    AddDecay(GenerateToneWithHarmonic(la0,beat/2,FS),...
    rise_time,set_time, disappear_time),...
    AddDecay(GenerateToneWithHarmonic(la0,beat/2,FS),...
    rise_time,set_time, disappear_time),...
    AddDecay(GenerateToneWithHarmonic(so0,beat/2,FS),...
    rise_time,set_time, disappear_time),...
    AddDecay(GenerateToneWithHarmonic(so0,beat/2,FS),...
    rise_time,set_time, disappear_time),...
    AddDecay(GenerateToneWithHarmonic(re0,beat/2,FS),...
    rise_time,set_time, disappear_time),...
    AddDecay(GenerateToneWithHarmonic(mi0,beat*2,FS),...
    rise_time,set_time, disappear_time),...
    AddDecay(GenerateToneWithHarmonic(0,beat*0.75,FS),...
    rise_time,set_time, disappear_time),...
    ...
    AddDecay(GenerateToneWithHarmonic(mi_1,beat*0.25,FS),...
    rise_time,set_time, disappear_time),...
    AddDecay(GenerateToneWithHarmonic(fa0,beat/2,FS),...
    rise_time,set_time, disappear_time),...
    AddDecay(GenerateToneWithHarmonic(fa0,beat/2,FS),...
    rise_time,set_time, disappear_time),...
    AddDecay(GenerateToneWithHarmonic(fa0,beat/2,FS),...
    rise_time,set_time, disappear_time),...
    AddDecay(GenerateToneWithHarmonic(mi0,beat/2,FS),...
    rise_time,set_time, disappear_time),...
    AddDecay(GenerateToneWithHarmonic(re0,beat/2,FS),...
    rise_time,set_time, disappear_time),...
    AddDecay(GenerateToneWithHarmonic(do0,beat/2,FS),...
    rise_time,set_time, disappear_time),...
    AddDecay(GenerateToneWithHarmonic(si_1,beat*2,FS),...
    rise_time,set_time, disappear_time),...
    AddDecay(GenerateToneWithHarmonic(la_1,beat/2,FS),...
    rise_time,set_time, disappear_time),...
    AddDecay(GenerateToneWithHarmonic(si_1,beat/2,FS),...
    rise_time,set_time, disappear_time),...
    AddDecay(GenerateToneWithHarmonic(do0,beat*2,FS),...
    rise_time,set_time, disappear_time),...
    AddDecay(GenerateToneWithHarmonic(re0,beat,FS),...
    rise_time,set_time, disappear_time),...
    AddDecay(GenerateToneWithHarmonic(si_1,beat*6,FS),...
    rise_time,set_time, disappear_time),...
    ...
    ...
    AddDecay(GenerateToneWithHarmonic(do0,beat*3,FS),...
    rise_time,set_time, disappear_time),...
    AddDecay(GenerateToneWithHarmonic(la_1,beat*3,FS),...
    rise_time,set_time, disappear_time),...
    AddDecay(GenerateToneWithHarmonic(si_1,beat*3,FS),...
    rise_time,set_time, disappear_time),...
    AddDecay(GenerateToneWithHarmonic(so_1,beat*3,FS),...
    rise_time,set_time, disappear_time),...
    AddDecay(GenerateToneWithHarmonic(do0,beat*3,FS),...
    rise_time,set_time, disappear_time),...
    AddDecay(GenerateToneWithHarmonic(la_1,beat*3,FS),...
    rise_time,set_time, disappear_time),...
    ...
    AddDecay(GenerateToneWithHarmonic(si_1,beat*1.5,FS),...
    rise_time,set_time, disappear_time),...
    AddDecay(GenerateToneWithHarmonic(la_1,beat/2,FS),...
    rise_time,set_time, disappear_time),...
    AddDecay(GenerateToneWithHarmonic(so_1,beat/2,FS),...
    rise_time,set_time, disappear_time),...
    AddDecay(GenerateToneWithHarmonic(mi_1,beat/2,FS),...
    rise_time,set_time, disappear_time),...
    AddDecay(GenerateToneWithHarmonic(mi_1,beat*2,FS),...
    rise_time,set_time, disappear_time),...
    AddDecay(GenerateToneWithHarmonic(0,beat,FS),...
    rise_time,set_time, disappear_time),...
    ...
    AddDecay(GenerateToneWithHarmonic(do0,beat*3,FS),...
    rise_time,set_time, disappear_time),...
    AddDecay(GenerateToneWithHarmonic(la_1,beat,FS),...
    rise_time,set_time, disappear_time),...
    AddDecay(GenerateToneWithHarmonic(0,beat*2,FS),...
    rise_time,set_time, disappear_time),...
    AddDecay(GenerateToneWithHarmonic(si_1,beat*2.5,FS),...
    rise_time,set_time, disappear_time),...
    AddDecay(GenerateToneWithHarmonic(so_1,beat/2,FS),...
    rise_time,set_time, disappear_time),...
    AddDecay(GenerateToneWithHarmonic(0,beat*3,FS),...
    rise_time,set_time, disappear_time),...
    AddDecay(GenerateToneWithHarmonic(do0,beat*3,FS),...
    rise_time,set_time, disappear_time),...
    AddDecay(GenerateToneWithHarmonic(la_1,beat,FS),...
    rise_time,set_time, disappear_time),...
    AddDecay(GenerateToneWithHarmonic(0,beat/2,FS),...
    rise_time,set_time, disappear_time),...
    AddDecay(GenerateToneWithHarmonic(si_1,beat/2,FS),...
    rise_time,set_time, disappear_time),...
    AddDecay(GenerateToneWithHarmonic(do0,beat,FS),...
    rise_time,set_time, disappear_time),...
    AddDecay(GenerateToneWithHarmonic(re0,beat/2,FS),...
    rise_time,set_time, disappear_time),...
    AddDecay(GenerateToneWithHarmonic(mi0,beat*5.5,FS),...
    rise_time,set_time, disappear_time),...
    };
sound(ConcatenateTones(tones,FS*beat/16),FS);